// GoLearn — Remote Learning Platform API
//
// @title           GoLearn API
// @version         1.0
// @description     Backend API for the GoLearn remote learning platform
// @termsOfService  http://swagger.io/terms/
//
// @contact.name   GoLearn Support
// @contact.email  support@golearn.io
//
// @license.name  MIT
// @license.url   https://opensource.org/licenses/MIT
//
// @host      localhost:8090
// @BasePath  /api
//
// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
// @description Type "Bearer " followed by your JWT token
package main

import (
	"log"

	"golearn/config"
	"golearn/database"
	"golearn/handlers"
	"golearn/middleware"

	_ "golearn/docs" // generated by swag init

	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

func main() {
	cfg := config.Load()
	database.Connect(cfg)

	router := gin.Default()

	// CORS — allow all origins for lab environment
	router.Use(cors.New(cors.Config{
		AllowAllOrigins:  true,
		AllowMethods:     []string{"GET", "POST", "PUT", "DELETE", "OPTIONS"},
		AllowHeaders:     []string{"Origin", "Content-Type", "Authorization"},
		ExposeHeaders:    []string{"Content-Length"},
		AllowCredentials: true,
	}))

	// Global rate limiting (5 req/s, burst 10)
	router.Use(middleware.RateLimit(cfg))

	// ── Public auth routes ────────────────────────────────────────────────
	auth := router.Group("/api/auth")
	{
		auth.POST("/register", handlers.Register(cfg))
		auth.POST("/login", handlers.Login(cfg))
	}

	// ── Protected API routes (JWT required) ──────────────────────────────
	api := router.Group("/api")
	api.Use(middleware.AuthRequired(cfg))
	{
		// Courses
		api.GET("/courses", handlers.ListCourses)
		api.GET("/courses/:id", handlers.GetCourse)
		api.POST("/courses", middleware.TeacherOnly(), handlers.CreateCourse)
		api.PUT("/courses/:id", middleware.TeacherOnly(), handlers.UpdateCourse)
		api.DELETE("/courses/:id", middleware.TeacherOnly(), handlers.DeleteCourse)

		// Lessons
		api.GET("/courses/:id/lessons", handlers.ListLessons)
		api.POST("/courses/:id/lessons", middleware.TeacherOnly(), handlers.CreateLesson)

		// Quiz
		api.GET("/lessons/:id/quiz", handlers.GetQuiz)
		api.POST("/lessons/:id/quiz", middleware.TeacherOnly(), handlers.CreateQuiz)
		api.POST("/quiz/:id/submit", handlers.SubmitQuiz)

		// Progress
		api.POST("/lessons/:id/complete", handlers.CompleteLesson)
		api.GET("/my/progress", handlers.GetMyProgress)
	}

	// ── WebSocket classroom ───────────────────────────────────────────────
	router.GET("/ws/classroom/:courseId", handlers.ClassroomWS(cfg))

	// ── Swagger UI ────────────────────────────────────────────────────────
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	log.Printf("GoLearn API running on :%s", cfg.Port)
	if err := router.Run(":" + cfg.Port); err != nil {
		log.Fatalf("server error: %v", err)
	}
}
