// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "GoLearn Support",
            "email": "support@golearn.io"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Authenticates a user and returns a JWT",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["auth"],
                "summary": "Login",
                "parameters": [{
                    "description": "Login credentials",
                    "name": "body",
                    "in": "body",
                    "required": true,
                    "schema": {"$ref": "#/definitions/handlers.LoginInput"}
                }],
                "responses": {
                    "200": {"description": "OK"},
                    "400": {"description": "Bad Request"},
                    "401": {"description": "Unauthorized"}
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Creates a student or teacher account",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["auth"],
                "summary": "Register a new user",
                "parameters": [{
                    "description": "User registration data",
                    "name": "body",
                    "in": "body",
                    "required": true,
                    "schema": {"$ref": "#/definitions/handlers.RegisterInput"}
                }],
                "responses": {
                    "201": {"description": "Created"},
                    "400": {"description": "Bad Request"},
                    "409": {"description": "Conflict"}
                }
            }
        },
        "/courses": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Returns paginated list of courses",
                "produces": ["application/json"],
                "tags": ["courses"],
                "summary": "List courses",
                "parameters": [
                    {"name": "page", "in": "query", "type": "integer"},
                    {"name": "limit", "in": "query", "type": "integer"},
                    {"name": "category", "in": "query", "type": "string"},
                    {"name": "sort", "in": "query", "type": "string"}
                ],
                "responses": {"200": {"description": "OK"}}
            },
            "post": {
                "security": [{"BearerAuth": []}],
                "description": "Teacher only",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["courses"],
                "summary": "Create a course",
                "parameters": [{
                    "description": "Course data",
                    "name": "body",
                    "in": "body",
                    "required": true,
                    "schema": {"$ref": "#/definitions/handlers.CourseInput"}
                }],
                "responses": {
                    "201": {"description": "Created"},
                    "400": {"description": "Bad Request"},
                    "403": {"description": "Forbidden"}
                }
            }
        },
        "/courses/{id}": {
            "get": {
                "security": [{"BearerAuth": []}],
                "produces": ["application/json"],
                "tags": ["courses"],
                "summary": "Get course by ID",
                "parameters": [{"name": "id", "in": "path", "required": true, "type": "integer"}],
                "responses": {
                    "200": {"description": "OK"},
                    "404": {"description": "Not Found"}
                }
            },
            "put": {
                "security": [{"BearerAuth": []}],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["courses"],
                "summary": "Update a course (owner teacher only)",
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "integer"},
                    {"description": "Updated course data", "name": "body", "in": "body", "required": true, "schema": {"$ref": "#/definitions/handlers.CourseInput"}}
                ],
                "responses": {
                    "200": {"description": "OK"},
                    "403": {"description": "Forbidden"},
                    "404": {"description": "Not Found"}
                }
            },
            "delete": {
                "security": [{"BearerAuth": []}],
                "tags": ["courses"],
                "summary": "Delete a course (owner teacher only)",
                "parameters": [{"name": "id", "in": "path", "required": true, "type": "integer"}],
                "responses": {
                    "200": {"description": "OK"},
                    "403": {"description": "Forbidden"},
                    "404": {"description": "Not Found"}
                }
            }
        },
        "/courses/{id}/lessons": {
            "get": {
                "security": [{"BearerAuth": []}],
                "produces": ["application/json"],
                "tags": ["lessons"],
                "summary": "List lessons for a course",
                "parameters": [{"name": "id", "in": "path", "required": true, "type": "integer"}],
                "responses": {"200": {"description": "OK"}, "404": {"description": "Not Found"}}
            },
            "post": {
                "security": [{"BearerAuth": []}],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["lessons"],
                "summary": "Add a lesson to a course (owner teacher only)",
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "integer"},
                    {"description": "Lesson data", "name": "body", "in": "body", "required": true, "schema": {"$ref": "#/definitions/handlers.LessonInput"}}
                ],
                "responses": {
                    "201": {"description": "Created"},
                    "403": {"description": "Forbidden"},
                    "404": {"description": "Not Found"}
                }
            }
        },
        "/lessons/{id}/quiz": {
            "get": {
                "security": [{"BearerAuth": []}],
                "tags": ["quiz"],
                "summary": "Get quiz for a lesson",
                "parameters": [{"name": "id", "in": "path", "required": true, "type": "integer"}],
                "responses": {"200": {"description": "OK"}, "404": {"description": "Not Found"}}
            },
            "post": {
                "security": [{"BearerAuth": []}],
                "consumes": ["application/json"],
                "tags": ["quiz"],
                "summary": "Create quiz for a lesson (teacher/owner only)",
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "integer"},
                    {"description": "Quiz data", "name": "body", "in": "body", "required": true, "schema": {"$ref": "#/definitions/handlers.QuizInput"}}
                ],
                "responses": {
                    "201": {"description": "Created"},
                    "403": {"description": "Forbidden"},
                    "409": {"description": "Conflict"}
                }
            }
        },
        "/quiz/{id}/submit": {
            "post": {
                "security": [{"BearerAuth": []}],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["quiz"],
                "summary": "Submit quiz answers",
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "integer"},
                    {"description": "Answers map", "name": "body", "in": "body", "required": true, "schema": {"$ref": "#/definitions/handlers.SubmitInput"}}
                ],
                "responses": {"200": {"description": "OK"}, "404": {"description": "Not Found"}}
            }
        },
        "/lessons/{id}/complete": {
            "post": {
                "security": [{"BearerAuth": []}],
                "tags": ["progress"],
                "summary": "Mark a lesson as completed",
                "parameters": [{"name": "id", "in": "path", "required": true, "type": "integer"}],
                "responses": {"200": {"description": "OK"}, "404": {"description": "Not Found"}}
            }
        },
        "/my/progress": {
            "get": {
                "security": [{"BearerAuth": []}],
                "produces": ["application/json"],
                "tags": ["progress"],
                "summary": "Get current user progress across all courses",
                "responses": {"200": {"description": "OK"}}
            }
        },
        "/ws/classroom/{courseId}": {
            "get": {
                "description": "Connect with ?token=JWT. Each courseId is an isolated room.",
                "tags": ["websocket"],
                "summary": "WebSocket classroom chat",
                "parameters": [
                    {"name": "courseId", "in": "path", "required": true, "type": "string"},
                    {"name": "token", "in": "query", "required": true, "type": "string"}
                ],
                "responses": {"101": {"description": "Switching Protocols"}}
            }
        }
    },
    "definitions": {
        "handlers.RegisterInput": {
            "type": "object",
            "required": ["name", "email", "password"],
            "properties": {
                "name":     {"type": "string"},
                "email":    {"type": "string"},
                "password": {"type": "string"},
                "role":     {"type": "string", "example": "student"}
            }
        },
        "handlers.LoginInput": {
            "type": "object",
            "required": ["email", "password"],
            "properties": {
                "email":    {"type": "string"},
                "password": {"type": "string"}
            }
        },
        "handlers.CourseInput": {
            "type": "object",
            "required": ["title"],
            "properties": {
                "title":       {"type": "string"},
                "description": {"type": "string"},
                "category":    {"type": "string"}
            }
        },
        "handlers.LessonInput": {
            "type": "object",
            "required": ["title"],
            "properties": {
                "title":     {"type": "string"},
                "content":   {"type": "string"},
                "video_url": {"type": "string"},
                "order":     {"type": "integer"}
            }
        },
        "handlers.QuizInput": {
            "type": "object",
            "required": ["title", "questions"],
            "properties": {
                "title":     {"type": "string"},
                "questions": {"type": "array", "items": {"$ref": "#/definitions/handlers.QuestionInput"}}
            }
        },
        "handlers.QuestionInput": {
            "type": "object",
            "required": ["text", "correct"],
            "properties": {
                "text":     {"type": "string"},
                "option_a": {"type": "string"},
                "option_b": {"type": "string"},
                "option_c": {"type": "string"},
                "option_d": {"type": "string"},
                "correct":  {"type": "string", "example": "a"}
            }
        },
        "handlers.SubmitInput": {
            "type": "object",
            "required": ["answers"],
            "properties": {
                "answers": {
                    "type": "object",
                    "additionalProperties": {"type": "string"}
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer \" followed by your JWT token",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8090",
	BasePath:         "/api",
	Schemes:          []string{"http"},
	Title:            "GoLearn API",
	Description:      "Backend API for the GoLearn remote learning platform",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
